// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeIepfsuWRzbHrFXRmU_cLKTBKeNvvaK8',
    appId: '1:383011175320:web:32102578882cca454149ed',
    messagingSenderId: '383011175320',
    projectId: 'stepgive-1f6d3',
    authDomain: 'stepgive-1f6d3.firebaseapp.com',
    storageBucket: 'stepgive-1f6d3.firebasestorage.app',
    measurementId: 'G-GWMBKC3T99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBvGv8xyEfU23leHpqHz3L-XXLgPSxShs',
    appId: '1:383011175320:android:b641ea852247b1ee4149ed',
    messagingSenderId: '383011175320',
    projectId: 'stepgive-1f6d3',
    storageBucket: 'stepgive-1f6d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUysDl4Y8xaiTw_ieq8wglXceBQypRh1I',
    appId: '1:383011175320:ios:f62fc1ec03c66d5f4149ed',
    messagingSenderId: '383011175320',
    projectId: 'stepgive-1f6d3',
    storageBucket: 'stepgive-1f6d3.firebasestorage.app',
    iosBundleId: 'com.example.runDonate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUysDl4Y8xaiTw_ieq8wglXceBQypRh1I',
    appId: '1:383011175320:ios:f62fc1ec03c66d5f4149ed',
    messagingSenderId: '383011175320',
    projectId: 'stepgive-1f6d3',
    storageBucket: 'stepgive-1f6d3.firebasestorage.app',
    iosBundleId: 'com.example.runDonate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeIepfsuWRzbHrFXRmU_cLKTBKeNvvaK8',
    appId: '1:383011175320:web:4d847e7c70847f3c4149ed',
    messagingSenderId: '383011175320',
    projectId: 'stepgive-1f6d3',
    authDomain: 'stepgive-1f6d3.firebaseapp.com',
    storageBucket: 'stepgive-1f6d3.firebasestorage.app',
    measurementId: 'G-0P2BGCJML7',
  );
}
